package de.vaadin.arto.einkaufsliste.einkaufsliste_db;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ArtikelEditorDesign extends VerticalLayout {
	protected TextField bezeichnung;
	protected TextField menge;
	protected Button buttonSave;
	protected Button buttonCancel;
	protected Button buttonDel;
	protected Button buttonAdd;

	public ArtikelEditorDesign() {
		Design.read(this);
	}
}
